# run "source aliases.zsh" to load aliases
alias env="source ../myenv/bin/activate"
alias denv="deactivate"
alias mmg="python manage.py makemigrations main_app"
alias mg="python manage.py migrate"
alias install="pip3 install -r requirements.txt"
alias run="python3 manage.py runserver"
alias suser="python3 manage.py createsuperuser"
alias freeze="pip3 freeze > requirements.txt"
alias shell="python3 manage.py shell"
alias db="python3 manage.py dbshell"
alias test="python3 manage.py test"
alias install="pip3 install -r requirements.txt"