# Generated by Django 4.0.6 on 2023-03-30 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_remove_store_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350)),
                ('price', models.FloatField(blank=True, null=True)),
                ('imgLink', models.URLField(blank=True, max_length=650, null=True)),
                ('link', models.URLField(blank=True, max_length=650, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wm_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350)),
                ('price', models.FloatField(blank=True, null=True)),
                ('imgLink', models.URLField(blank=True, max_length=650, null=True)),
                ('link', models.URLField(blank=True, max_length=650, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_product', to='main_app.amazon_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('wm_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wm_product', to='main_app.wm_product')),
            ],
        ),
    ]
