# Generated by Django 4.0.6 on 2023-03-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_amazon_product_wm_product_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazon_product',
            old_name='imgLink',
            new_name='amazon_imgLink',
        ),
        migrations.RenameField(
            model_name='amazon_product',
            old_name='link',
            new_name='amazon_link',
        ),
        migrations.RenameField(
            model_name='amazon_product',
            old_name='price',
            new_name='amazon_price',
        ),
        migrations.RenameField(
            model_name='amazon_product',
            old_name='title',
            new_name='amazon_title',
        ),
        migrations.RenameField(
            model_name='wm_product',
            old_name='imgLink',
            new_name='wm_imgLink',
        ),
        migrations.RenameField(
            model_name='wm_product',
            old_name='link',
            new_name='wm_link',
        ),
        migrations.RenameField(
            model_name='wm_product',
            old_name='price',
            new_name='wm_price',
        ),
        migrations.RenameField(
            model_name='wm_product',
            old_name='title',
            new_name='wm_title',
        ),
    ]
